language: c
compiler:
  - clang
  - gcc

env:
  - OPTIONS=-Duse_context=OFF
  - OPTIONS=-Duse_context=ON
  - OPTIONS=-Dno_floats=ON

addons:
  apt:
    sources:
      - george-edison55-precise-backports
    packages:
      - cmake
      - cmake-data
script:
- "./build.sh all test"
